### ISSUE TITLE
QuickLaunch panel is not always on top

### ISSUE THREAD

**Issue by ArachneRomBor** [DinVision/QuickLaunch#4]
Sometimes it happens that the QuickLaunch panel (application) is not on top, so it is not possible to "shift" the panel out.
So I have to use Alt+Tab to activate the QuickLaunch application and then it is on top again.

The QuickLaunch window probably does not have the "Always on top" flag set.
Or could some other application force its own window to the foreground and thus "hide" the QuickLaunch window? I have not been able to see which application I am using could do this.

**Comment by DinVision** [comment]
In my tests and daily use, the Quick Launch App stays on top of all usual applications like Office App (Word, Excel, Outlook), Browsers (Chrome, Edge, Firefox), Windows apps (Notepad, Calculator, Control Panel). The App is already set to stay on top. The only cases I find is, it does not stay on top of the built-in Windows Start Menu and Windows Taskbar.

Following is my recent test.
[YouTube - Window On Top Test](https://www.youtube.com/watch?v=c8FGzt-WZXI)
I will keep checking on this, if can provide specific app or scenarios where it does not stay on top, I can test further. Thanks.

**Comment by ArachneRomBor** [comment]
Thanks for the reply. I'll try to track it down and see under what circumstances it happens.
It happened to me again yesterday, and even though I minimized all opened windows, moving the mouse over the bar of the "hidden" application window, didn't make the window "shift out".

**Comment by DinVision** [comment]
There is a rare occasional glitch where the Quick Launch toolbar may not reappear from auto-hide mode. That may be what you experienced. If this happens, click on the strip and drag it to a visible area once. It should then continue to work as usual. I haven't been able to consistently reproduce or fix this issue yet.

**Comment by DinVision** [comment]
There is a rare occasional glitch where the Quick Launch  may not reappear from auto-hide mode. That may be what you experienced. This can happen if we move the mouse cursor hovering over the Tooltip of the icons. 

Here is video showing this issue [Auto-Hide Test](https://www.youtube.com/watch?v=8DPAzTadm04)

I will see if this can be fixed in the program. For now, to minimize this issue, please increase the margin of the Quick Launch. In any case, if it happens, click on the strip and drag it to a visible area once. It should then continue to work as usual.

If you don't need Tooltip, you can disable it in the INI file. Set "ShowToolTip=No"

![Image](https://github.com/user-attachments/assets/90731bcf-95d8-4204-92ac-e46ce4e1744d)

**Comment by DinVision** [comment]
The Auto-hide glitch related to Tooltip is fixed in the version 1.0.62.0, please update the App and try again.

**Comment by ArachneRomBor** [comment]
The problem with the hidden Quick Launch Toolbar window still persists.
Even increasing the window margin did not help.
And I still can't track under what circumstances, or which application, it causes.
So for now I'll leave it as is, I still have the option to "activate" the Quick Launch window via Alt+Tab if the window is hidden.
